import os
from typing import Literal, TypeAlias

ALG_LEN = 2
KDF_PARAM_LEN = 8
KEY_ID_LEN = 8
KEY_LEN = 32
SALT_LEN = 32
CHECKSUM_LEN = 32
SIG_LEN = 64
SIG_0_LEN = ALG_LEN + KEY_ID_LEN + SIG_LEN

KEYNUM_PK_LEN = KEY_ID_LEN + KEY_LEN
KEYNUM_SK_LEN = KEY_ID_LEN + (KEY_LEN << 1) + CHECKSUM_LEN
PUBLIC_KEY_LEN = ALG_LEN + KEYNUM_PK_LEN
SECRET_KEY_LEN = (ALG_LEN * 3) + SALT_LEN + (KDF_PARAM_LEN * 2) + KEYNUM_SK_LEN

SIG_EXT = "minisig"
BYTE_ORDER: Literal["little", "big"] = "little"
DEFAULT_SK_PATH = "~/.minisign/minisign.key"

UNTRUSTED_COMMENT_PREFIX = "untrusted comment: "
UNTRUSTED_COMMENT_PREFIX_LEN = len(UNTRUSTED_COMMENT_PREFIX)
TRUSTED_COMMENT_PREFIX = "trusted comment: "
TRUSTED_COMMENT_PREFIX_LEN = len(TRUSTED_COMMENT_PREFIX)
DEFAULT_SIGNATURE_UNTRUSTED_COMMENT = "signature from minisign secret key"
TRUSTED_COMMENT_MAX_LEN = 8192 - TRUSTED_COMMENT_PREFIX_LEN

PathLike: TypeAlias = str | os.PathLike[str]
