"""Compatibility tests ported from the Go and Rust minisign implementations.

Sources:
https://github.com/jedisct1/go-minisign/tree/a09352b57a22f418b9ad8edcfe901eb4be8d40e5
https://github.com/jedisct1/rust-minisign/tree/c5f9f4b5d6a5a55afbb2dbbae8a342245be8d7c7
"""

from __future__ import annotations

import pytest

from minisign import (
    Error,
    KeyPair,
    ParseError,
    PublicKey,
    SecretKey,
    Signature,
)

GO_PUBLIC_KEY = b"RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3"

GO_LEGACY_SIGNATURE = (
    b"untrusted comment: signature from minisign secret key\n"
    b"RWQf6LRCGA9i59SLOFxz6NxvASXDJeRtuZykwQepbDEGt87ig1BNpWaVWuNrm73YiIiJbq71Wi+dP9eKL8OC351vwIasSSbXxwA=\n"
    b"trusted comment: timestamp:1635442742\tfile:test\n"
    b"0YteLgV960ia80vnA/fHbvkyjl/IoP/HNOCaZfrF0CdhAlp7ok+Tpkya+VpWPX5C/Is3q8a/kEDSY7fBmmgJCg==\n"
)

GO_PREHASHED_SIGNATURE = (
    b"untrusted comment: signature from minisign secret key\n"
    b"RUQf6LRCGA9i559r3g7V1qNyJDApGip8MfqcadIgT9CuhV3EMhHoN1mGTkUidF/z7SrlQgXdy8ofjb7bNJJylDOocrCo8KLzZwo=\n"
    b"trusted comment: timestamp:1635443258\tfile:test\thashed\n"
    b"/cj37GK60vryibFn+ftOgbCvW9NKhKYgjVpFFQUcWPAnjO23wrvVDTt7cloNC06maoBli9q6qwZDXXoaxweICQ==\n"
)

# Generated by `minisign -G -W`.
GO_UNENCRYPTED_SECRET_KEY = (
    b"untrusted comment: minisign encrypted secret key\n"
    b"RWQAAEIyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOItWpGuGQbG4C9WXaxEYLgZ2xxuqfbuZmDgAhQ8Unot8t7SyxZ0nVh0gESesJ6Ay57fGFJ9T1ajVmanT7MFMCCDbPZ8uqDcSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=\n"
)
GO_UNENCRYPTED_PUBLIC_KEY = (
    b"untrusted comment: minisign public key B141866BA4568B38\n"
    b"RWQ4i1aka4ZBsR0gESesJ6Ay57fGFJ9T1ajVmanT7MFMCCDbPZ8uqDcS\n"
)

# Generated by `minisign -G` with passphrase "testpass".
GO_ENCRYPTED_SECRET_KEY = (
    b"untrusted comment: minisign encrypted secret key\n"
    b"RWRTY0IyxYlIT2FS5i8PqThE9swBemvY94JDIMqo75UBK3XO/aUAAAACAAAAAAAAAEAAAAAAUhlw8nsT1tuVUekS6Je3iUwoWFdb1xiLonO35G66RiVvM/QgrBtnDa0Dhbt7H3oYMh4aFLiNxMs24gzXqHVsvRVthMeF08fN8r6siRdBpiBZ36B7rox2lmYIYgg5T8qt7tOxo9doAxk=\n"
)
GO_ENCRYPTED_PUBLIC_KEY = (
    b"untrusted comment: minisign public key 9149E58DCF22FFC1\n"
    b"RWTB/yLPjeVJkXKtzk1nZI0TU+fZPqEaIzg1ABHwfnI8pZNWtifIpWBq\n"
)

RUST_VALID_PUBLIC_KEY = b"RWRzq51bKcS8oJvZ4xEm+nRvGYPdsNRD3ciFPu1YJEL8Bl/3daWaj72r"
RUST_INVALID_PUBLIC_KEY = b"RWQt7oYqpar/yePp+nonossdnononovlOSkkckMMfvHuGc+0+oShmJyN5Y"
RUST_LEGACY_SIGNATURE = (
    b"untrusted comment: signature from minisign secret key\n"
    b"RWQf6LRCGA9i59SLOFxz6NxvASXDJeRtuZykwQepbDEGt87ig1BNpWaVWuNrm73YiIiJbq71Wi+dP9eKL8OC351vwIasSSbXxwA=\n"
    b"trusted comment: timestamp:1555779966\tfile:test\n"
    b"QtKMXWyYcwdpZAlPF7tE2ENJkRd1ujvKjlj1m9RtHTBnZPa5WKU5uWRs5GoP5M/VqE81QFuMKI5k/SfNQUaOAA=="
)
RUST_PREHASHED_SIGNATURE = (
    b"untrusted comment: signature from minisign secret key\n"
    b"RUQf6LRCGA9i559r3g7V1qNyJDApGip8MfqcadIgT9CuhV3EMhHoN1mGTkUidF/z7SrlQgXdy8ofjb7bNJJylDOocrCo8KLzZwo=\n"
    b"trusted comment: timestamp:1556193335\tfile:test\n"
    b"y/rUw2y8/hOUYjZU71eHp/Wo1KZ40fGy2VJEDl34XMJM+TX48Ss/17u3IvIfbVR1FkZZSNCisQbuQY+bHwhEBg=="
)


@pytest.mark.parametrize(
    "encoded_signature, prehashed",
    (
        (GO_LEGACY_SIGNATURE, False),
        (GO_PREHASHED_SIGNATURE, True),
    ),
)
def test_go_signature_vectors(encoded_signature: bytes, prehashed: bool):
    signature = Signature.from_bytes(encoded_signature)
    assert signature.is_prehashed() is prehashed
    PublicKey.from_base64(GO_PUBLIC_KEY).verify(b"test", signature)


def test_go_unencrypted_key_vector():
    secret_key = SecretKey.from_bytes(GO_UNENCRYPTED_SECRET_KEY)
    public_key = PublicKey.from_bytes(GO_UNENCRYPTED_PUBLIC_KEY)
    assert not secret_key.is_encrypted()
    assert secret_key.get_public_key().to_base64() == public_key.to_base64()


def test_go_encrypted_key_vector():
    secret_key = SecretKey.from_bytes(GO_ENCRYPTED_SECRET_KEY)
    public_key = PublicKey.from_bytes(GO_ENCRYPTED_PUBLIC_KEY)
    assert secret_key.is_encrypted()
    secret_key.decrypt("testpass")
    assert not secret_key.is_encrypted()
    assert secret_key.get_public_key().to_base64() == public_key.to_base64()


def test_go_encrypted_key_rejects_wrong_password():
    secret_key = SecretKey.from_bytes(GO_ENCRYPTED_SECRET_KEY)
    encoded = bytes(secret_key)
    with pytest.raises(Error, match="wrong password"):
        secret_key.decrypt("nope")
    assert bytes(secret_key) == encoded


@pytest.mark.parametrize("prehashed", (False, True))
def test_go_sign_roundtrip(prehashed: bool):
    secret_key = SecretKey.from_bytes(GO_UNENCRYPTED_SECRET_KEY)
    public_key = PublicKey.from_bytes(GO_UNENCRYPTED_PUBLIC_KEY)
    data = b"the quick brown fox jumps over the lazy dog"
    signature = secret_key.sign(
        data,
        prehash=prehashed,
        untrusted_comment="hello world",
        trusted_comment="file:fox.txt",
    )
    parsed = Signature.from_bytes(bytes(signature))
    assert parsed.untrusted_comment == "hello world"
    assert parsed.trusted_comment == "file:fox.txt"
    public_key.verify(data, parsed)


def test_go_sign_defaults():
    signature = SecretKey.from_bytes(GO_UNENCRYPTED_SECRET_KEY).sign(b"hi")
    assert signature.untrusted_comment == "signature from minisign secret key"
    assert signature.trusted_comment.startswith("timestamp:")


@pytest.mark.parametrize(
    "untrusted_comment, trusted_comment",
    (
        ("a\nb", None),
        (None, "a\nb"),
        (None, "foo\x01bar"),
        (None, "a" * 8200),
    ),
)
def test_go_sign_rejects_invalid_comments(
    untrusted_comment: str | None,
    trusted_comment: str | None,
):
    secret_key = SecretKey.from_bytes(GO_UNENCRYPTED_SECRET_KEY)
    with pytest.raises(ParseError):
        secret_key.sign(
            b"x",
            untrusted_comment=untrusted_comment,
            trusted_comment=trusted_comment,
        )


def test_rust_public_key_vectors():
    PublicKey.from_base64(RUST_VALID_PUBLIC_KEY)
    with pytest.raises(ParseError):
        PublicKey.from_base64(RUST_INVALID_PUBLIC_KEY)


@pytest.mark.parametrize(
    "encoded_signature, prehashed",
    (
        (RUST_LEGACY_SIGNATURE, False),
        (RUST_PREHASHED_SIGNATURE, True),
    ),
)
def test_rust_signature_vectors(encoded_signature: bytes, prehashed: bool):
    signature = Signature.from_bytes(encoded_signature)
    assert signature.is_prehashed() is prehashed
    assert signature.untrusted_comment == "signature from minisign secret key"
    assert signature.trusted_comment.startswith("timestamp:")
    PublicKey.from_base64(GO_PUBLIC_KEY).verify(b"test", signature)


def test_rust_signature_rejects_modified_data():
    key_pair = KeyPair.generate()
    signature = key_pair.secret_key.sign(b"test")
    with pytest.raises(Error):
        key_pair.public_key.verify(b"test2", signature)


def test_rust_empty_password_roundtrip():
    key_pair = KeyPair.generate()
    key_pair.secret_key.encrypt("")
    assert key_pair.secret_key.is_encrypted()
    stored = SecretKey.from_bytes(bytes(key_pair.secret_key))
    stored.decrypt("")
    assert not stored.is_encrypted()
    key_pair.public_key.verify(b"test", stored.sign(b"test"))
